fix: support for popler >= 26.05 font encoding change
Poppler version 26.05.0 changed the return type of
gfx8bit->getEncoding() from char** to const std::array<const char*,256>&.
this caused a compilation error due to type incompatibility:
    error: assigning to 'char **' from incompatible type 'const std::array<const char *, 256>
    error: no viable conversion from 'const std::array<const char *, 256>' to 'char **'